- name: nozzreg.csv
  axes:
    labels:
      - "$x$, мм"
      - '$q_w$, МВт/м$^2$'
    x limits: [-400, 600]
    y limits: [0, 14]
    precision: [0, 0]
    single x axis: false
  charts:
    legend:
      - "эксперимент"
      - "расчет NOZZReg"
      - "расчет ПРМ"
    style: # ["стиль линии", "стиль маркера"]
      - ["-", ""]
      - ["-", ""]
      - ["", "+"]
  figure size: [ 16.5, 10 ]
  dpi: 300