#style задается следующим образом: ['linestyle', 'marker', 'linewidth', 'markersize', 'markeredgewidth']

# ----------------------------------------------------------------------------------------
#- name: harper_nozzle.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$y$, м'
#    x limits: [-0.5, 1.5]
#    y limits: [0, 0.42]
#    precision: [1, 1]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

#- name: nozzreg.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$q_w$, МВт/м$^2$'
#    x limits: [-0.4, 0.6]
#    y limits: [0, 15]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '1'
#      - '2'
#      - '3'
#    style:
#      - ['-','','2','1','1']
#      - ['-','','2','1','1']
#      - ['','.','1','2','1']
#  figure size: [8.5, 6]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: blhd_comparison.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$\delta$, мм'
#    x limits: ~
#    y limits: [0.2, 0.9]
#    precision: [1, 1]
#    single x axis: true
#  charts:
#    legend:
#      - 'BLHD'
#      - 'ЛОГОС'
#    style:
#      - ['','.','1','10','1']
#      - ['','+','1','10','1']
#  figure size: [8.5, 6]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: injection_comparison_contour.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$y$, м'
#    x limits: [0, 0.3]
#    y limits: [0, 0.1]
#    precision: [1, 2]
#    single x axis: false
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

#- name: injection_comparison.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$\zeta_T$'
#    x limits: [0, 0.3]
#    y limits: [0, 1]
#    precision: [1, 1]
#    single x axis: false
#  charts:
#    legend:
#      - 'ПРМ'
#      - 'формула'
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: RBAS_T_profiles_st.csv
#  axes:
#    labels:
#      - 'Толщина, мм'
#      - '$T$, K'
#    x limits: [0, 6.5]
#    y limits: [200, 1200]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '0,1'
#      - '1'
#      - '5'
#      - '10'
#      - '11'
#      - '12'
#      - '13'
#      - '14'
#    style: ~
#  figure size: [ 8.5, 8 ]
#  dpi: 300

#- name: RBAS_T_profiles.csv
#  axes:
#    labels:
#      - 'Толщина, мм'
#      - '$T$, K'
#    x limits: [0, 4.5]
#    y limits: [200, 1200]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '0,1'
#      - '1'
#      - '5'
#      - '10'
#      - '11'
#      - '12'
#      - '13'
#      - '14'
#    style: ~
#  figure size: [ 8.5, 8 ]
#  dpi: 300

#- name: RBAS_qw.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$q_{w}$, кВт/м$^2$'
#    x limits: [6.8, 7.7]
#    y limits: [0, 520]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '$t=0$ с'
#      - '$t=11$ с'
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

#- name: RBAS_mf.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$m_{w}$, кг/(с $\cdot$ м$^2$)'
#    x limits: [6.8, 7.7]
#    y limits: ~
#    precision: [1, 2]
#    single x axis: false
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: temps_comparison_K.csv
#  axes:
#    labels:
#      - '$t$, с'
#      - '$T, K$'
#    x limits: [0, 100]
#    y limits: [200, 1800]
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '1'
#      - '2'
#      - '3'
#      - '4'
#    style: ~
#  figure size: [ 8.5, 6 ]
#  dpi: 300

#- name: eff_T.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$\zeta_T$'
#    x limits: [0.05, 0.2]
#    y limits: [0, 1]
#    precision: [2, 1]
#    single x axis: false
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: efficiency_t.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - 'Эффективность'
#    x limits: [-0.3, 0.2]
#    y limits: [0, 1]
#    precision: [1, 1]
#    single x axis: false
#  charts:
#    legend:
#      - '$\zeta_T$'
#      - '$\zeta_{TT}$'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: eff_G.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$g_{вд} \cdot 10^{-2}$'
#    x limits: [0.05, 0.2]
#    y limits: [0, 1.2]
#    precision: [2, 1]
#    single x axis: false
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: T_wall_comparison.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$T$, K'
#    x limits: [0.05, 0.2]
#    y limits: [500, 2200]
#    precision: [2, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '$T_w$ внутр.'
#      - '$T_w$ внеш.'
#      - '$T_w$ внеш. эксперимент'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: hew.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$h_{ew}$, МДж/кг'
#    x limits: [-0.3, 0.2]
#    y limits: [-5, 0]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: vkladysh_temps.csv
#  axes:
#    labels:
#      - '$t$, с'
#      - '$T$, K'
#    x limits: [0, 10]
#    y limits: [0, 3500]
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - 'Эксп. ЦК'
#      - 'Эксп. Wei-hua'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#
#- name: vkladysh_v_wall.csv
#  axes:
#    labels:
#      - '$t$, с'
#      - '$v_{w}$, мм/с'
#    x limits: [0, 10]
#    y limits: [0, 0.35]
#    precision: [0, 2]
#    single x axis: false
#  charts:
#    legend:
#      - 'Мгновенная, эксп. ЦК'
#      - 'Средняя, эксп. ЦК'
#      - 'Мгновенная, эксп. Wei-hua'
#      - 'Средняя, эксп. Wei-hua'
#    style:
#      - ['-','','1']
#      - ['--','','1']
#      - ['-','','1']
#      - ['--','','1']
#  figure size: [ 16.5, 12 ]
#  dpi: 300
#
#- name: vkladysh_temps_1.csv
#  axes:
#    labels:
#      - '$t$, с'
#      - '$T$, К'
#    x limits: [0, 10]
#    y limits: [0, 3000]
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - 'Эксп. ЦК'
#      - 'Эксп. Wei-hua'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#
#- name: vkladysh_v_wall_1.csv
#  axes:
#    labels:
#      - '$t$, с'
#      - '$v_{w}$, мм/с'
#    x limits: [0, 11]
#    y limits: [0, 0.08]
#    precision: [0, 2]
#    single x axis: false
#  charts:
#    legend:
#      - 'Расчет по эксп. ЦК'
#      - 'Расчет по эксп. Wei-hua'
#      - 'Эксп. ЦК'
#      - 'Эксп. Wei-hua'
#    style:
#      - ['-','','1']
#      - ['-','','1']
#      - ['','P','1']
#      - ['','P','1']
#  figure size: [ 16.5, 10 ]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: sslines.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$y$, м'
#    x limits: [-0.15, 0.15]
#    y limits: [0, 0.18]
#    precision: [2, 2]
#    single x axis: false
#  charts:
#    legend:
#      - 'Контур $t=0$ с'
#      - 'Контур $t=34$ с'
#      - 'Сверхзвуковая линия $t=0$ с'
#      - 'Сверхзвуковая линия $t=34$ с'
#      - 'Минимальное сечение $t=0$ с'
#      - 'Минимальное сечение $t=34$ с'
#    style:
#      - ['-','','1']
#      - ['-','','1']
#      - ['-','','0.8']
#      - ['-','','0.8']
#      - [':','','1.5']
#      - [':','','1.5']
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: sslines_nondim.csv
#  axes:
#    labels:
#      - '$x/d_{кр}$'
#      - '$y/d_{кр}$'
#    x limits: [-2, 2]
#    y limits: [0, 2.5]
#    precision: [0, 1]
#    single x axis: false
#  charts:
#    legend:
#      - '1'
#      - '2'
#      - '3'
#      - '4'
#      - '5'
#      - '6'
#    style:
#      - ['-','','1','1','1']
#      - ['-','','1','1','1']
#      - ['-','','0.8','1','1']
#      - ['-','','0.8','1','1']
#      - ['--','','1.5','1','1']
#      - ['--','','1.5','1','1']
#  figure size: [ 8.5, 8 ]
#  dpi: 300

#- name: caverna.csv
#  axes:
#    labels:
#      - '$x$, мм'
#      - '$y$, мм'
#    x limits: ~
#    y limits: [122, 128]
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '0'
#      - '4'
#      - '7'
#      - '10'
#      - '12'
#      - '17'
#      - '22'
#      - '25'
#      - '28'
#      - '34'
#    style:
#      - ['-','','1.5','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#      - ['-','','0.7','1','1']
#  figure size: [ 8.5, 8 ]
#  dpi: 300

#- name: kolomna_ablation_data.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$\delta$, мм'
#    x limits: [-0.2, 1]
#    y limits: [0, 14]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - 'Расчет'
#      - 'Эксперимент 1'
#      - 'Эксперимент 2'
#      - 'Эксперимент 3'
#      - 'Эксперимент 4'
#    style:
#      - ['-','','1'] # linestyle, marker, linewidth
#      - ['','+','1']
#      - ['','+','1']
#      - ['','+','1']
#      - ['','+','1']
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: p_wall_t0.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$p_{w}$, Па'
#    x limits: [0.26, 0.28]
#    y limits: ~
#    precision: [3, 3]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#- name: p_wall_t12.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$p_{w}$, Па'
#    x limits: [0.26, 0.28]
#    y limits: ~
#    precision: [3, 3]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#- name: p_wall_t17.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$p_{w}$, Па'
#    x limits: [0.26, 0.28]
#    y limits: ~
#    precision: [3, 3]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#- name: p_wall_t22.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$p_{w}$, Па'
#    x limits: [0.26, 0.28]
#    y limits: ~
#    precision: [3, 3]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#- name: p_wall_t34.csv
#  axes:
#    labels:
#      - '$x$, м'
#      - '$p_{w}$, Па'
#    x limits: [0.26, 0.28]
#    y limits: ~
#    precision: [3, 3]
#    single x axis: true
#  charts:
#    legend: ~
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300

#- name: delta_S.csv
#  axes:
#    labels:
#      - '$\delta_{max}$, мм'
#      - '$S_{max}$, мм'
#    x limits: [1.5, 3.5]
#    y limits: [2, 10]
#    precision: [1, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '1'
#      - '2'
#      - '3'
#      - '4'
#      - '5'
#      - '6'
#    style:
#      - ['-','','1','1','1']
#      - ['','X','1','6','0.1']
#      - ['','X','1','6','0.1']
#      - ['','X','1','6','0.1']
#      - ['','X','1','6','0.1']
#      - ['','X','1','6','0.1']
#  figure size: [ 8.5, 8 ]
#  dpi: 300

# ----------------------------------------------------------------------------------------

#- name: kolomna_h(T).csv
#  axes:
#    labels:
#      - '$T$, K'
#      - '$h$, кДж/кг'
#    x limits: ~
#    y limits: ~
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '0,08 МПа'
#      - '1 МПа'
#      - '5 МПа'
#      - '9 МПа'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#
#- name: kolomna_cp(T).csv
#  axes:
#    labels:
#      - '$T$, K'
#      - '$c_p$, Дж/(кг $\cdot$ K)'
#    x limits: ~
#    y limits: ~
#    precision: [0, 0]
#    single x axis: false
#  charts:
#    legend:
#      - '0,08 МПа'
#      - '1 МПа'
#      - '5 МПа'
#      - '9 МПа'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300
#
#- name: kolomna_mu(T).csv
#  axes:
#    labels:
#      - '$T$, K'
#      - '$\mu \cdot 10^5$, Па $\cdot$ с'
#    x limits: ~
#    y limits: ~
#    precision: [0, 1]
#    single x axis: false
#  charts:
#    legend:
#      - '0,08 МПа'
#      - '1 МПа'
#      - '5 МПа'
#      - '9 МПа'
#    style: ~
#  figure size: [ 16.5, 10 ]
#  dpi: 300